### ISSUE TITLE
Seems that v 7.0.0 won't build with Elm 0.15.1

### ISSUE THREAD

**Issue by twopoint718** [circuithub/elm-html-shorthand#4]
I got this message when attempting to install my package which uses `elm-html-shorthand`:

```
Downloading circuithub/elm-bootstrap-html
Downloading circuithub/elm-html-extra
Downloading circuithub/elm-html-shorthand
Downloading elm-lang/core
Downloading evancz/elm-html
Downloading evancz/elm-http
Downloading evancz/virtual-dom
Packages configured successfully!
Detected errors in 1 module.
## ERRORS in dependency circuithub/elm-html-shorthand 7.0.0 ####################

This error probably means that the 'circuithub/elm-html-shorthand' has some
package constraint that is too permissive. You should definitely inform the
maintainer to get this fixed and save other people from this pain.

In the meantime, you can attempt to artificially constrain things by adding
some extra constraints to your elm-package.json though that is not
the long term solution.
```

My own `elm-package.json` looks like this:

```
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/USER/PROJECT.git",
    "license": "BSD3",
    "source-directories": [
        ".",
        "src"
    ],
    "exposed-modules": [],
    "dependencies": {
        "circuithub/elm-bootstrap-html": "6.3.0 <= v < 7.0.0",
        "circuithub/elm-html-shorthand": "8.0.0 <= v < 9.0.0",
        "elm-lang/core": "2.1.0 <= v < 3.0.0",
        "evancz/elm-html": "3.0.0 <= v < 4.0.0",
        "evancz/elm-http": "1.0.0 <= v < 2.0.0"
    },
    "elm-version": "0.15.0 <= v < 0.16.0"
}
```

I'm not sure what the issue is, a first look at the deps for 7.0.0 seem okay. I did notice one bit of strangeness: https://github.com/circuithub/elm-html-shorthand/commit/edad2a85d36883d2dc50351e9304222cd3c23cb0 in this commit it looks like the version goes from 8.0.1 to 7.0.0. Am I reading that correctly? Would that cause problems?

Thanks!

**Comment by rehno-lindeque** [comment]
I'm afraid I've been having trouble getting `elm-html-shorthand` to compile with Elm 0.15.1 due to this issue: https://github.com/elm-lang/elm-compiler/issues/993  (unfortunately hacking the order for the documentation on this module seems like it will be a huge due to the sheer size of it). For now I've just been compiling with Elm 0.15 while waiting for that issue to be resolved.

I think I saw some more issues reported (fixed?) recently wrt package constraints bugging out - it's probably worth searching through the elm issue trackers...

> in this commit it looks like the version goes from 8.0.1 to 7.0.0. Am I reading that correctly? Would that cause problems?

It hasn't caused me any problems but there was this weird thing (when Elm went from 0.14 to 0.15) where it seemed as though versions of the packaged I'd published before no longer existed and I was forced by the elm tooling to rewind to an earlier version tag. I assumed this was just a temporary hiccup... I don't _think_ that this is the cause of your issue, but I can't be sure.

Sorry for the trouble! If you figure out a solution please let me know... I could also add you as a collaborator on this package if you'd like to try to publish a new version yourself. It looks as though it might be necessary to actually publish in order to debug the constraints.

**Comment by rehno-lindeque** [comment]
Oh but by the way, the latest version of `elm-html-shorthand` is `9.0.1`. I see you have it as `< 9.0.0` in your `package.json`. Have you tried with `9.0.1 <= v < 10.0.0`?

It looks like I might have to adjust the constraints in `elm-bootstrap-html`. I'll give that a try quickly.

**Comment by rehno-lindeque** [comment]
Yep, it looks like a couple of things broke my packages with the more recent elm tooling. I can't seem to bump `elm-bootstrap-html` at the moment and the error message doesn't really make any sense:

```
Error: Unable to get documentation.json for circuithub/elm-bootstrap-html 6.3.1
Cannot decode Value from: "Internal.BtnParam"
```

However, I did manage to quickly bump `elm-html-extra` and `elm-html-shorthand` for you - perhaps that will help.
